Completed full integration of sign up process
bottlenose-dolphins/worldgate-track-trace pull request #22
Opened 2023-01-24 18:38 UTC by JeffS97

# Description

Fixes [BDTT-37](https://bottlenose.atlassian.net/browse/BDTT-37)

[screen-capture.webm](https://user-images.githubusercontent.com/40801372/214379392-b6b2e640-2a8d-450e-b557-c8315e493092.webm)

List all acceptance criterias of user story and indicate which has been solved previously and which is solved currently
- [x] Customer leaves any field blank
- [x] Customer enters invalid email address
- [x] Customer enters existing username
- [x] Customer enters a password less than 8 characters
- [x] Customer keys in valid inputs for all fields

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
# Checklist:

- [x] I have added the appropriate labels to my PR
- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-01-27 16:05 UTC, charmjj requested changes

2023-01-29 06:27 UTC, JeffS97 commented on app/src/components/signUp/phoneInput.jsx
> +// singaporePhoneNumberRegex = /^[0-9]{8}$/;
Removed

2023-01-29 06:27 UTC, JeffS97 commented on app/src/components/signUp/index.jsx
> +            // TODO: Redirect to home page/dashboard
Added navigation to sign in page

2023-01-29 06:28 UTC, JeffS97 commented on app/src/components/signUp/index.jsx
> +            setError("User already exists in the system");
Changed

2023-01-29 06:28 UTC, JeffS97 commented on app/src/components/signUp/registerButton.jsx
>  function RegisterButton() {
Refactor in future sprints would be better i think

2023-01-29 06:28 UTC, JeffS97 commented on app/src/components/signUp/index.jsx
> +                <div className='pt-5 text-red-500'>{ error }</div>
Changed

2023-01-29 06:28 UTC, JeffS97 commented on app/src/components/signUp/index.jsx
> +        const res = await signUp(email, username, password, phone, company);
Changed

2023-01-29 07:12 UTC, charmjj approved these changes

2023-01-29 07:12 UTC, merged