Bdtt 12 varun backend
bottlenose-dolphins/worldgate-track-trace pull request #29
Opened 2023-02-10 18:25 UTC by VaruneshBala

# Description
BDTT_12
Fixes [Jira ticket #]()

List all acceptance criterias of user story and indicate which has been solved previously and which is solved currently
- [x] XXX (solved)
- [x] XXX (solving)
- [ ]

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Migration

# Checklist:

- [X] I have added the appropriate labels to my PR
- [X] My code follows the style guidelines of this project
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-02-10 18:27 UTC, VaruneshBala commented
can only return one container number so far need to find a way to return all

need to test viewShipments function bc i cant download invokes on my local machine

2023-02-18 17:36 UTC, VaruneshBala commented
viewallshipments works now pls check
included all the core svcs on docker-compose
made some changes to port number in all the dockerfiles for core svcs for brayden (changed to port 80 and did port mapping in docker -compose)

2023-02-19 16:20 UTC, prussianman requested changes
Thanks for the laborious work, mustn't have been easy to test all the code. 

However, there are some issues:

1. There is a port conflict between 2 containers sharing port 8081.

2. The core APIs were to use ports 5000+ , while the scrapers port 8080+, however, they are both using 8080+ (there will be conflicts when merged)

3. The PROD dockerfiles are not PROD ready (this is fine, I will open another branch to work on them)

2023-02-19 20:33 UTC, prussianman commented
LGTM

2023-02-19 20:33 UTC, prussianman approved these changes
LGTM

2023-02-19 20:45 UTC, merged

2023-02-20 04:56 UTC, VaruneshBala commented on services/backend/core/export_cont.py
> +# Retrieve CONT_N from EXPORT_REF_CONT using EXPORT_REF_N (NOT ABLE TO GET ALL VALUES ONLY THE FIRST VALUE RETRIEVED)
Nope I can retrieve all now. Forgot to remove the comment

2023-02-20 04:56 UTC, VaruneshBala commented on services/backend/core/export.py
> +    export_ref_n = Export.query.filter_by(wguser_id=wguser_id).first().export_ref_n
Oh so not one wguser_id = one import/export_ref_num?

2023-02-20 04:56 UTC, VaruneshBala commented on services/backend/core/export.py
> +    export_ref_n = Export.query.filter_by(wguser_id=wguser_id).first().export_ref_n
i will make changes tonight

2023-02-20 04:57 UTC, VaruneshBala commented on services/backend/core/import.py
> +            "uguser_id": self.wguser_id
changed

2023-02-20 04:58 UTC, VaruneshBala commented on services/backend/core/import.py
> +    import_ref_n = Import.query.filter_by(wguser_id=wguser_id).first().import_ref_n
will change tonight

2023-02-20 04:58 UTC, VaruneshBala commented on services/backend/core/viewAllShipments.py
> +# NOT ABLE TO INSTALL INVOKES ON MY END CAN SOMEONE HELP ME INSTALL AND TRY THIS OUT? all the other 4 services works individually
Nope forgot to remove comment

2023-02-21 06:47 UTC, VaruneshBala commented
Working on the necessary changes in a new branch (bdtt-12-varun-viewallshipment-BackEnd)