Bdtt 19 customers get notified of shipment status
bottlenose-dolphins/worldgate-track-trace pull request #61
Opened 2023-04-05 15:21 UTC by rohanmk99

# Description
https://bottlenose.atlassian.net/jira/software/projects/BDTT/boards/1?selectedIssue=BDTT-19

Upon Clicking Subscribe in ViewAllShipments page the following happens:
addsubscription is called in the complex scrapper via method in shipment.jsx
This calls simple microservice subscription.py (add method) Which checks if subscription already exist, if it doesnt then adds new row into subscription and the current status
<img width="536" alt="image" src="https://user-images.githubusercontent.com/73184733/230124794-7ddf190c-4500-4b3d-bc08-151544f4d93f.png">

Then in complex scrapper there is a function called sendsms. That calls getsubscription in subscription.py to get all active subscriptions. Then we go through the list and obtain the container number. Using the container number we call the scrapper to obtain status. Then we check if new status is different from original status when subscribed. If status is different we obtain phone number of user from user.py getnumber function. Then we send sms using twilio api.
<img width="823" alt="image" src="https://user-images.githubusercontent.com/73184733/230125393-08fc795a-584d-4d86-adc4-c9b670c5ddcf.png">

<img width="823" alt="image" src="https://user-images.githubusercontent.com/73184733/230127042-6e83aed1-b5d8-4a91-ac33-5ad8e823a030.png">

Then we have scheduler.py that calls the sendsms every 24 hours and runs in the background to check if status has changed.
<img width="823" alt="image" src="https://user-images.githubusercontent.com/73184733/230126731-03d36750-0b35-499d-bd72-fff7d6248dea.png">

Then when we click unsubscribe we call the delete subscription method via shipment.jsx and then complex microservice deletesubscription that finally invokes simple microservice subscription. This removes the record from the subscription table.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor
- [ ] Migration

# Checklist:

- [ ] I have added the appropriate labels to my PR
- [ ] My code follows the style guidelines of this project
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-04-05 15:33 UTC, rohanmk99 commented
reopen

2023-04-06 20:26 UTC, pandaponn requested changes
Good work on getting the notification feature to work. I have not been able to test it personally as my phone number isn't verified but based on the code, it seems like it would work as intended. 

Additionally, I think YMLU scraper does not work as the scraper is not returning status.

Also, could you implement some sort of visual response in the UI when user subscribes/unsubscribes to a shipment? (Similar to what Charmaine has for logging in and logging out) And disable the unsubscribe button if user is not subscribed, vice-versa.

Would also be good if users can subscribe/unsubscribe from the /status page and not only through the dashboard. (But this is not crucial)

Please help to make the changes ASAP as we are short on time and I also need to integrate this ASAP, otherwise good job 👍🏻

2023-04-06 20:26 UTC, pandaponn commented on services/backend/core/complex_scraper.py
> +        shipment_type="ctr"
Why is shipment_type and directions hardcoded here? Wouldn't that mean if the shipment is a BL or EXPORT, then the SMS won't send?

2023-04-06 20:26 UTC, pandaponn commented on services/backend/core/complex_scraper.py
> +                to = "+65"+str(phone_number)
Can you verify my number so that I can test the Twilio notification on my phone as well?

2023-04-07 15:18 UTC, charmjj requested changes
see comments

2023-04-07 15:18 UTC, charmjj commented on services/frontend/app/package.json
> -    "start": "PORT=80 react-scripts start",
be careful of what you commit. put back this PORT=80

2023-04-07 15:18 UTC, charmjj commented on services/frontend/app/src/components/ViewShipments/ViewShipmentComponent.jsx
> +              <div className="inline-flex">
![image](https://user-images.githubusercontent.com/71003267/230633212-1becb016-6ad5-417e-a70f-bfa97bec9ce5.png)

Shipment cards and your subscribe notification buttons are misaligned. Can you make sure that they are all of same length? Or you can try putting your subscribe/unsubscribe buttons into the card as well. Most importantly following Zhi Hao's point, we need some indication of whether the user has subscribed to notifications for the particular shipment or not

2023-04-09 07:57 UTC, JeffS97 commented on services/frontend/app/package.json
> -    "start": "PORT=80 react-scripts start",
Done

2023-04-10 18:47 UTC, pandaponn approved these changes
LGTM

2023-04-10 18:48 UTC, charmjj approved these changes
lgtm

2023-04-10 18:48 UTC, merged